# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
    assets:
        calendar_css:
            inputs:
                - %kernel.root_dir%/../vendor/arshaw/fullcalendar/build/out/fullcalendar.css
                - @GoogleCalendarBundle/Resources/public/css/calendar.css
            filters:
                - cssrewrite
            output: css/calendar.css
        jquery_ui_css:
            inputs:
                - %kernel.root_dir%/../vendor/jquery/jquery-ui/themes/base/jquery.ui.core.css
                - %kernel.root_dir%/../vendor/jquery/jquery-ui/themes/base/jquery.ui.dialog.css
                - %kernel.root_dir%/../vendor/jquery/jquery-ui/themes/base/jquery.ui.theme.css
            filters:
                - cssrewrite
            output: css/jquery-ui.css
        jquery_js:
            inputs:
                - %kernel.root_dir%/../vendor/sonata-project/jquery-bundle/Sonata/jQueryBundle/Resources/public/jquery-1.8.3.js
                - %kernel.root_dir%/../vendor/sonata-project/jquery-bundle/Sonata/jQueryBundle/Resources/public/jquery-ui-1.8.23.js
                - %kernel.root_dir%/../vendor/sonata-project/jquery-bundle/Sonata/jQueryBundle/Resources/public/jquery-ui-i18n.js
            output: js/jquery.js
        calendar_js:
            inputs:
                - %kernel.root_dir%/../vendor/arshaw/fullcalendar/build/out/fullcalendar.js
                - %kernel.root_dir%/Resources/public/js/date.format.js
                - @GoogleCalendarBundle/Resources/public/js/calendar.js
            output: js/calendar.js